### ISSUE TITLE
Debugging Quarkus Apps - http logging/tracing

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#111]
Reach out to Michał Szynkiewicz and arrange a date for a Quarkus Insights using http logging /tracing.

@michalszynkiewicz - Max said you're interested in doing a session. I'm trying to get this set on the calendar. How soon do you feel doing the session?

**Comment by michalszynkiewicz** [comment]
I'll think about it and let you know

**Comment by insectengine** [comment]
Ok... thanks!

**Comment by michalszynkiewicz** [comment]
I think in three months will be safe :)
I need to get to know the current state of this and quite possibly implement a few improvements first.

@geoand you have done work in this area recently, are you interested in working together on presenting this topic?

**Comment by geoand** [comment]
I was thinking about it, but we don't have a critical piece in place yet (and probably won't for a few months)

**Comment by insectengine** [comment]
Thanks for the update... let's circle back to this later.

**Comment by doogle-oss** [comment]
Are we having a logging tracing session for quarkus soon?

**Comment by insectengine** [comment]
@geoand @michalszynkiewicz  - What do you guys think? Are we in a position to present on this topic?

**Comment by geoand** [comment]
Let me come back to you next week after I check out some things

**Comment by geoand** [comment]
I think we should wait for some relevant features coming in Vert.x 4.3 before we do this

**Comment by insectengine** [comment]
@geoand  - Is there a timeline for Vert.x 4.3 to be released?

**Comment by geoand** [comment]
Not sure

**Comment by insectengine** [comment]
@geoand @michalszynkiewicz  - I see that Vert.X 4.3 was released in May. Is this a topic we're ready to cover?

**Comment by michalszynkiewicz** [comment]
I unfortunately won't have time for it...

**Comment by geoand** [comment]
The Vert.x release did not contain the feature I hoped for unfortunately

**Comment by insectengine** [comment]
@michalszynkiewicz  @geoand  ah ok. Should we close this issue then?

**Comment by geoand** [comment]
Probably yeah

**Comment by insectengine** [comment]
Putting this issue away since the features never came to fruition.
