### ISSUE TITLE
Quarkus Scheduler

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#119]
Topic: Quarkus Schedular
Description: TBD
Guest: Martin Kouba
Twitter: @martunek

**Comment by mkouba** [comment]
### Agenda

1. Intro
2. Extensions
3. Simple API example
4. Cron-like expressions
5. Dev UI
6. Configuration
7. Delayed execution
8. Concurrent Execution
9. Conditional Execution
10. Non-blocking methods
11. Management API
12. Metrics
13. Use cases for quarkus-quartz

### Materials and links

- [Quarkus - scheduler reference guide](https://quarkus.io/guides/scheduler-reference)
- [Quarkus - scheduler getting started](https://quarkus.io/guides/scheduler) / [Quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/scheduler-quickstart)
- [Quarkus - Quartz clustering guide](https://quarkus.io/guides/quartz) / [Quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/quartz-quickstart)
- [Quartz cron syntax](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html#format)
- [Quarkus default blocking thread pool config](https://quarkus.io/guides/all-config#quarkus-core_quarkus-core-quarkus-core)

**Comment by insectengine** [comment]
https://youtu.be/MwJB93hhHak
