### ISSUE TITLE
CDI Non-standard Features

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#120]
Topic: CDI Non-standard Features
Description: Martin Kouba @martunek will join us next week to discuss the latest CDI Non-standard Features in Quarkus.
Guest: Martin Kouba
Twitter: @martunek

**Comment by mkouba** [comment]
### Agenda

1. Intro - CDI vs ArC
2. Qualified Injected Fields
3. Simplified Constructor Injection
4. Removing Unused Beans
5. Enabling Beans for Build Profile/Property
6. Default Beans
7. Interception of Static Methods
8. Container-managed Concurrency
9. Caching the Result of Programmatic Lookup
10. Declaratively Choose Beans That Can Be Obtained by Programmatic Lookup
11. Injecting Multiple Bean Instances Intuitively
12. Exceptions Thrown By An Asynchronous Observer Method

### Materials and Links

- https://quarkus.io/guides/cdi-reference
- https://quarkus.io/guides/cdi
- https://quarkus.io/guides/cdi-integration
- https://www.cdi-spec.org/
- https://jakarta.ee/specifications/cdi/

**Comment by mkouba** [comment]
Slides: https://docs.google.com/presentation/d/1tpsJgonwPdyF6h2jCvKEHPPlZNXtTyieUuOQnNPch_8/edit?usp=sharing

**Comment by insectengine** [comment]
https://youtu.be/XybonqP34hM
