### ISSUE TITLE
Qute with Quarkus

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#121]
Topic: Qute with Quarkus
Description: Martin Kouba @martunek joins us to discuss what's new with Qute and Quarkus.
Guest: Martin Kouba
Twitter: @martunek

**Comment by mkouba** [comment]
### Agenda

1. Intro - what's Qute?
2. The easiest way to try Qute - `Qute.fmt()`
3. Search for templates in all application archives
4. Strict Rendering & `@CheckedTemplate.requireTypeSafeExpressions()`
5. Template Extension Methods - [namespaces](https://quarkus.io/guides/qute-reference#namespace_extension_methods), [new built-in extensions](https://quarkus.io/guides/qute-reference#built-in-template-extension)
6. Accessing Static Fields and Methods
7. Improved enum support - `@TemplateEnum`, `{#when}`
8. Global Variables
9. Evaluation of `CompletionStage` and `Uni`
10. [Loop Section](https://quarkus.io/version/main/guides/qute-reference#loop_section) - Iteration Metadata Prefix
11. Include Section and User Tags - Unified Behavior
12. [Content Filters](https://quarkus.io/version/main/guides/qute-reference#content-filters)
13. Type-safe Message Bundles - improved validation and localization
14. Default values for the [`{#let}` section](https://quarkus.io/version/main/guides/qute-reference#let_section) parameters

### Materials and Links

- https://quarkus.io/guides/qute-reference

**Comment by insectengine** [comment]
https://www.youtube.com/watch?v=nH-27gOp0h4
