### ISSUE TITLE
Quinoa... Quarkus Modern UI with no hassles

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#124]
title: Quinoa... Quarkus Modern UI with no hassles
description: Andy Damevin @ia3andy joins us to discuss how the Quinoa extension takes care of all the Web UI build/wiring/dev-mode hassles to let you focus of your web application logic.

twitter: ia3andy

**Comment by ia3andy** [comment]
@insectengine in the hand it seems to be "Quarkus Modern UI with no hassle" (no s)

**Comment by insectengine** [comment]
https://youtu.be/ya8To5V1QUU
