### ISSUE TITLE
Extension CodeStarts

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#133]
Title: Using Quarkus CodeStarts
Description:  Andy Damevin @ia3andy gives us a tour of the Quarkus CodeStarts. What are they? What code they provide and how to use them in extensions. Explore the future of CodeStarts.
Guest: Andy Damevin
Twitter: @ia3andy

**Comment by ia3andy** [comment]
@insectengine August 22?

**Comment by ia3andy** [comment]
Title: A tour of the Quarkus Codestarts
Description: 
- The Codestart code generator
- What is an Extension Codestart and what kind of code should it provide
- Codestarts vs JHipster (and other)
- Creating a new Quarkiverse extension with a Codestart
- Adding a codestart to a Quarkiverse extension
- Codestart testing
- The future of codestarts

**Comment by insectengine** [comment]
@ia3andy - August 22 works... we'll secure that spot.

How about this for title/description:

Title: Using Quarkus CodeStarts
Description: Andy Damevin @ia3andy gives us a tour of the Quarkus CodeStarts. What's are they? What code they provide and how to use them in extensions. Explore the futures of CodeStarts.

**Comment by insectengine** [comment]
https://youtu.be/lLyVDqVK8cE
