### ISSUE TITLE
The latest in writing GitHub bots and GitHub Actions with Quarkus

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#136]
Proposed title: “The latest in writing GitHub bots with Quarkus”

Proposed description: “Guillaume Smet @gsmet discusses new features like comment-based commands and GitHub Actions and how they help you write GitHub bots in Quarkus”

**Comment by gsmet** [comment]
I would go with:

Title: The latest in writing GitHub bots and GitHub Actions with Quarkus.
Description: “Guillaume Smet @gsmet discusses new features like comment-based commands and GitHub Actions and how they help you write GitHub bots and GitHub Actions in Quarkus”

**Comment by insectengine** [comment]
@gsmet - You prefer Sept 19th or 26th?

**Comment by gsmet** [comment]
26th is safer for me to have something to present for GitHub Actions.

**Comment by insectengine** [comment]
The 26th it is!

**Comment by insectengine** [comment]
https://youtu.be/hzXO0Do9dMM
