### ISSUE TITLE
Debezium and Quarkus -- A Match Made in Heaven?

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#150]
Title: Debezium and Quarkus -- A Match Made in Heaven?

Descripton: Gunnar Morling and Chris Cranford join us to discuss running Debezium embedded into Quarkus apps (why and how), the  Debezium Server, and what's new in Debezium?

Guests:  Gunnar Morling and Chris Cranford 

Twitter: @gunnarmorling, @crancran77

**Comment by gunnarmorling** [comment]
// CC @Naros

**Comment by insectengine** [comment]
https://youtu.be/MQR1SLJVpgM
