### ISSUE TITLE
10 things I like about Quarkus

### ISSUE THREAD

**Issue by coiouhkc** [quarkusio/quarkus-insights#153]
Title: 10 things I like about Quarkus (as a reference to "10 things I hate about you")

Description: Alexei Bratuhin from OpenValue Düsseldorf will describe his path from the dark to the light side of force and will show several of the features he likes most about Quarkus - features that greatly improve and contribute to a better developer experience allowing to concentrate on clean design instead of struggling with the platform.

Kind: Hands-on-lab

Source: https://github.com/coiouhkc/short-and-sweet-quarkus-intro

**Comment by coiouhkc** [comment]
Alternatively (or additionally), focus on Quarkus + Database-Rider (see https://github.com/database-rider/database-rider) - I plan to prepare an internal short&sweet anyway.

**Comment by insectengine** [comment]
Hello Alexei,

I'm sorry we missed this issue! It would be very interesting to talk with you about having you on Quarkus Insights!

Please email me at jcobb@redhat.com so we can discuss further.

**Comment by insectengine** [comment]
https://youtube.com/live/cU-2witNthQ
