### ISSUE TITLE
What's new in Infinispan?

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#154]
Proposed title: What's new in Infinispan?
Proposed Description: Katia Aresti @karesti Fabio Massimo Ercoli @FabioMErcoli joins us to discuss the new features and updates in the Infinispan Client.
Guest(s): Katia Aresti & Fabio Massimo Ercoli
Twitter: @karesti @FabioMErcoli

**Comment by karesti** [comment]
@insectengine Fabio Massimo Ercoli  will be joining me for the talk! @fax4ever

**Comment by insectengine** [comment]
https://youtu.be/qcjrGlRimYU
