### ISSUE TITLE
What's new with Quarkus Superheroes

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#155]
Proposed Title: What's new with Quarkus Superheroes

Proposed Description: Can you believe its been a year since the [Quarkus Superheroes](https://github.com/quarkusio/quarkus-super-heroes) sample application was released? Let's take a close look at all the cool new things that have been added to it over the past year!

Guests: Eric Deandrea & Antonio Goncalves
Twitter: @edeandrea  @agoncal

**Comment by edeandrea** [comment]
How about just "What's new with the Quarkus Superheroes" for a title?

And for description:
Can you believe its been a year since the [Quarkus Superheroes](https://github.com/quarkusio/quarkus-super-heroes) sample application was released? Let's take a close look at all the cool new things that have been added to it over the past year!

**Comment by agoncal** [comment]
@edeandrea If you want I can introduce the genesis of the sample (based on a workshop) and then you move on to presenting the sample itself (and how it evolved from the workshop)

**Comment by edeandrea** [comment]
We could do that as an intro for sure. I'll have a few slides as well and we can talk about it.

**Comment by edeandrea** [comment]
This is whats on my "list" of things to talk about:

- Constant updates to latest Quarkus versions
- Schema registry/Apache Avro/Apicurio
- Simple UI (Quarkus Qute) in heroes/villains
- MongoDB with Liquibase in fights
- KafkaCompanion in fights/event-statistics ITs
- Multi-arch images (& only single native image)
- SmallRye Stork service discovery/client load balancing
- OpenTelemetry integration (w/Jaeger UI/Otel collector)
- JMeter
- Azure Container apps magic script
- Pact contract testing
    - Show how its implemented
    - Show Pact broker

**Comment by insectengine** [comment]
https://youtu.be/H9yK0xnExeA
