### ISSUE TITLE
Quarkus Helm in Action

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#156]
Proposed Title: Quarkus Helm in Action
Proposed Description: TBD

Guest: Jose Carvajal Hilario
Twitter: @jcarvajalh

**Comment by tqvarnst** [comment]
I love the topic. It's vital that we, in this episode, explain how this can help with a fully automated loop for developing using DevOps principles. Showing both that through Quarkus config, we can control how specific values are generated, but without requiring deep knowledge of Helm. We also need to explain that users that think this is too much "magic" can also use custom helm charts. We must clarify that this enables Quarkus developers to do DevOps more efficiently and safer.

**Comment by Sgitario** [comment]
Slides: https://github.com/Sgitario/quarkus-insights-helm/blob/main/%5B06-02-23%5D%20Quarkus%20Insights%20%23116%20-%20Continuous%20delivery%20with%20Quarkus%20Helm%20and%20ArgoCD.pdf

Link: https://www.youtube.com/watch?v=95GsShVW6rY

**Comment by insectengine** [comment]
Added slide link to YT description
