### ISSUE TITLE
The Quarkus Frontend Rainbow... Why Quarkus is the best framework for full stack developers.

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#158]
Proposed Title: The Quarkus Frontend Rainbow... Why Quarkus is the best framework for full stack developers?
Proposed Description: Join us as Andy Damevin and Stéphane Épardaud show us Quarkus' front end capabilities using Quinoa and Renarde.

Guest: Andy Damevin & Stéphane Épardaud
Twitter: @ia3andy  @UnFroMage

**Comment by ia3andy** [comment]
@insectengine not sure if you saw but I added this: https://github.com/quarkusio/quarkus-insights/issues/178

I will soon start working on a few blog posts and youtube video:
- Quarkus Web Bundler how to use
- Create Quarkus htmx web apps with Renarde & Web Bundler
- The Quarkus Frontend rainbow. Why is Quarkus the best framework for full stack developers?

Not sure what order would fit best but I think we could have different Quarkus Insight.

cc @maxandersen

**Comment by insectengine** [comment]
https://youtube.com/live/C9JDsIrcTWI
