### ISSUE TITLE
What's New with Mutiny

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#164]
Proposed Title: What's New with Mutiny
Proposed Description: Julien Ponge @jponge & Clement Escoffier @clementplop will discuss the current state of Mutiny as of version 2, and why we have decided to switch to the JDK Flow APIs instead of the legacy Reactive Streams APIs.

Guests: Julien Ponge and Clement Escoffier

Twitter: @jponge @clementplop

**Comment by insectengine** [comment]
@jponge @cescoffier

**Comment by jponge** [comment]
Description:

We will discuss the current state of Mutiny as of version 2, and why we have decided to switch to the JDK Flow APIs instead of the legacy Reactive Streams APIs.

Twitter: `@jponge`

**Comment by insectengine** [comment]
updated

**Comment by insectengine** [comment]
https://youtube.com/live/RRs4DJJUSx8
