### ISSUE TITLE
JPAStreamer Quarkus Extension

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#169]
Proposed title: JPAStreamer Quarkus Extension
Proposed description: TBD

Guests: Julia Gustafsson
Guest twitter handles: Julia Gustafsson discusses how the JPAStreamer makes the process of writing Hibernate queries more intuitive and less time-consuming while leaving your existing codebase intact.

Dates:  April 24th

**Comment by julgus** [comment]
Hi, as April 24 is approaching I just wanted to check in with you and discuss my participation. Would it be okay to show a few slides to set the scene for JPAStreamer, and then perform a live demo of a Hibernate/Panache/JPAStreamer application?

**Comment by insectengine** [comment]
https://youtube.com/live/f2ZNVDhFmkU
