### ISSUE TITLE
How to Contribute: Quarkus's documentation revolution.

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#176]
How to contribute to Quarkus? What is the diataxis framework? Why make the change? How can the community participate? etc.

Title: How to Contribute to Quarkus Docs
Description: TBD

Guest: Stefan Sitani
Twitter: TBD

**Comment by inoxx03** [comment]
@insectengine When we discussed having a contribution-focused episode earlier in a recent marketing & messaging call, I remember we considered covering code and docs contributions in the same episode (Which makes sense, IMHO).

Do we still want to do it that way or do we want 2 episodes about contributing, with one of them being specifically about docs.

I'm fine either way (can provide content for a full episode if we got that way.)
I'm just spitballin' here :)

@maxandersen @tqvarnst @insectengine  What do you think could work best?

**Comment by insectengine** [comment]
I'm good with either format. @maxandersen  - thoughts?

@inoxx03  -  Are you available to do this on any of these dates? July 10, 17, 24?

**Comment by insectengine** [comment]
@inoxx03  - Thoughts on this topic and/or timing when you'd be comfortable doing the session?

**Comment by insectengine** [comment]
@maxandersen @tqvarnst  @inoxx03  - Hi Stefan... I wanted to connect back with you regarding doing a docs contribution specific episode. We have dates later in October available: Oct 16th, 23rd, and 30th. Do any of those dates work for you?
