### ISSUE TITLE
Quarkus Web Bundler

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus-insights#178]
title: Quarkus Web Bundler, Supersonic full-stack web-app for all developers 
description: Andy Damevin @ia3andy and  Erik Jan de Wit  @edewit join us to discuss how the Web Bundler extension. Create full-stack web apps quickly and easily. It offers zero-configuration bundling for your web app scripts (JS, JSX, TS, TSX), dependencies (Bootstrap, htmx, jQuery, Lit, etc.), and styles (CSS, SCSS, SASS). 

twitter: ia3andy

**Comment by insectengine** [comment]
Sorry @ia3andy ! I totally missed this! Would love to get this on the schedule. Does July 10, 17 or 24th work for you both?

**Comment by insectengine** [comment]
https://youtube.com/live/nnu1k3WKtaM
