### ISSUE TITLE
What's new in Hibernate Search

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#180]
Proposed Title: What's new in Hibernate Search
Proposed Description:  Yoann Rodiere @yoannrodiere joins us to give us an update on what's new and different in Hibernate Search.

Guests: Yoann Rodiere
Twitter: @yoannrodiere

**Comment by insectengine** [comment]
https://youtube.com/live/0-e4wkRwTIo

**Comment by yrodiere** [comment]
Slides: https://yrodiere.github.io/presentation/2023-11-quarkus-insights-whats-new-hibernate-search/

Demo 1 (search): https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-feature-examples/search-advanced

Demo 2 (outbox polling): https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-outbox-polling
