### ISSUE TITLE
Hibernate 7.1 & Vector Search

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#191]
Proposed Title:Hibernate 7.1 & Vector Search
Proposed Description: Yoann Rodière & Marko Bekhta join us to discuss how to go beyond full-text search and enrich it with vectors using Hibernate Search.

Guests: Yoann Rodière & Marko Bekhta
Twitter: @yoannrodiere @that_java_guy

**Comment by yrodiere** [comment]
There was a typo in my email, it's actually Hibernate Search 7.1, sorry :)

Here's a link to the relevant epic: https://hibernate.atlassian.net/browse/HSEARCH-4949

**Comment by yrodiere** [comment]
Slides: https://yrodiere.github.io/presentation/2023-11-quarkus-insights-whats-new-hibernate-search/

Demo 1 (search): https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-feature-examples/search-advanced

Demo 2 (outbox polling): https://github.com/hibernate/hibernate-demos/tree/main/hibernate-search/hsearch-outbox-polling

**Comment by yrodiere** [comment]
FWIW this session wasn't done at all; #180 was about Hibernate Search 6.2, so no vector search. We can still do another session about Hibernate Search 7.1 and Vector Search specifically, though this will take a bit more time.

If you're not interested, that's fine too, of course.

**Comment by gsmet** [comment]
I think we should do it. Vector search has a lot of traction at the moment.

**Comment by insectengine** [comment]
Sorry about that!  Reopened.

**Comment by insectengine** [comment]
@yrodiere  - are you able to do this session on January 22nd?

**Comment by yrodiere** [comment]
@insectengine Sorry but that's unlikely; we'll need the feature released and integrated into Quarkus first.
Even if we manage to get that into Quarkus 3.7 (which is ambitious), January 22nd would be a tight schedule.

Can I get back to you when I have a more precise idea of the timeline?

**Comment by insectengine** [comment]
Certainly... will keeping this in the queue.

**Comment by insectengine** [comment]
hello @yrodiere, checking in with you to see if we have any movement on this?

**Comment by yrodiere** [comment]
Hey @insectengine . As expected we missed the deadline to get this into Quarkus 3.7. So unfortunately we won't be able to expose it in Quarkus until 3.9 [at the end of March](https://quarkus.io/blog/our-plans-for-quarkus-3-7-3-8-3-9-released/#quarkus-3-9). I think it might be best if we wait until then? Otherwise we'll just be demoing something people can't use yet...

Also, pinging @marko-bekhta who I'd definitely like to join, or even lead this session :)

**Comment by insectengine** [comment]
Makes sense... we'll keep tabs on this.

**Comment by insectengine** [comment]
@yrodiere & @marko-bekhta - I wanted to circle back with the both of you about this session. Would you guys be available to do this session on either May 20th or May 27th?

**Comment by marko-bekhta** [comment]
Hi @insectengine we've talked with Yoann, and we think we can do a session on May 20th.

**Comment by marko-bekhta** [comment]
Hey @insectengine just wanted to check with you whether this session is still planned for May 20th or... 😃

**Comment by maxandersen** [comment]
It is NOT on May 20th (public holiday in Europe). @insectengine should give update later today about what future date are possible.

**Comment by insectengine** [comment]
@marko-bekhta @yrodiere - Sorry this slipped through the cracks. As Max pointed out, we're not doing a session next Monday the 20th. I'd love to get this on the schedule in late May/ early July. would either May 24th or July 1st work for you all?

**Comment by yrodiere** [comment]
I'd rather not do it on May 24th as I'll be away, but it can be done without me if necessary; I'll let Marko decide.
July 1st would work for me.

**Comment by marko-bekhta** [comment]
ok, July it is then 😃

**Comment by insectengine** [comment]
Excellent! I've sent an invite to you both. BTW...any suggestion for a session description?

**Comment by marko-bekhta** [comment]
Thanks! 

> BTW...any suggestion for a session description?

hmmmmmmmmm 🤔🤔🤔🤔  maybe:

> Yoann and Marko will join us to discuss how to go beyond full-text search and enrich it with vectors using Hibernate Search. 

🙈

**Comment by yrodiere** [comment]
Hey @insectengine I'd like to stress what I said a few months ago:

> There was a typo in my email, it's actually Hibernate Search 7.1, sorry :)

This will be about Hibernate *Search* 7.1, not Hibernate 7.1 (which most people would understand as Hibernate ORM 7.1)
I guess it's too late for the tweet, but you might want to adjust further communication :)

**Comment by insectengine** [comment]
Ugh... updated on socials for monday (and created a new event in restream with the name fix)

**Comment by insectengine** [comment]
https://youtube.com/live/ThH8sJC69zU
