### ISSUE TITLE
Quarkus Observability

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#192]
Proposed Title: Quarkus Observability
Proposed description: Bruno Baptista @brunobat_ shows how observability connects metrics and tracing to give better insights into the developer experience.

Guest: Bruno Baptista
twitter: @brunobat_

**Comment by brunobat** [comment]
Will see if some blog posts are created in advance to support the presentation.
Also I hope to have a new devservice to show.

**Comment by insectengine** [comment]
https://youtube.com/live/_ylTaPcNHg0
