### ISSUE TITLE
What's new with Superheroes

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#204]
Title: What's new with Superheroes
Description: Eric Deandrea joins us to discuss the latest tech and features integrated into the Quarkus Superheroes sample application.

Guest: Eric Deandrea
Twitter: @edeandrea

**Comment by edeandrea** [comment]
Does @agoncal want to join as well?

**Comment by agoncal** [comment]
Well, well. It depends when is the episode scheduled for. Despite some holidays, I don't have much to say about adding the new AI features... that have yet to be implemented (if our talk is accepted of course ;o)

**Comment by edeandrea** [comment]
It'll be February 5. We're just going to talk about whats new in the last year. All the stuff we've added in 2023 (lots of stuff). Not necessarily the "new" stuff we've discussed recently that have yet to be implemented.

Totally up to you.

**Comment by agoncal** [comment]
The week of the 5th of Feb is my week of holidays. So I won't be available. Count me in next time to talk about the AI stuff ;o)

**Comment by edeandrea** [comment]
Happy holidays!

**Comment by insectengine** [comment]
https://youtube.com/live/W_QREL1nEGI
