### ISSUE TITLE
Quarkus and HTMX

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#207]
Title: Quarkus and HTMX
Description (proposed): Ever considered trying Quarkus and HTMX together? HTMX is a very small Javascript library that creates  a javascript free “Single Page App” looking app. Let’s give it a try, live, and see how easy it is to set everything up with Quarkus.

Guests: Andy Damevin & Stéphane Épardaud
Twitter: @ia3andy  @UnFroMage

**Comment by ia3andy** [comment]
Don't you mean Quarkus & htmx?

**Comment by insectengine** [comment]
Old habits die hard. Fixed.

**Comment by insectengine** [comment]
https://youtube.com/live/zQUkmQsGSQc
