### ISSUE TITLE
How to create your own Quarkus extension

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#212]
Title (proposed): How to create your own Quarkus extension
Description : Holly Cummins discusses the basics, tips and tricks of creating your own Quarkus extensions.

Guests: Holly Cummins, Emil Lefkof (Melloware) ??

**Comment by insectengine** [comment]
@holly-cummins - do you think this is something we can do this summer?

**Comment by holly-cummins** [comment]
> @holly-cummins - do you think this is something we can do this summer?

Yes, I think so. I'd forgotten we hadn't already done it!

**Comment by insectengine** [comment]
Any preference on timing? We're open July 15th on. ;)

**Comment by insectengine** [comment]
https://youtube.com/live/90FEj1zqjWQ
