### ISSUE TITLE
Qute - the fundamentals

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#214]
Title (proposed): Introduction to Qute
Description (proposed): Martin Kouba discusses the basics of Qute, the templating engine which allows to build web applications using server-side templates.

Guest: Martin Kouba
Twitter: @martunek

**Comment by insectengine** [comment]
Pinged Martin via email (May 6th).

**Comment by mkouba** [comment]
Demo app: https://github.com/mkouba/qute-insights

**Comment by insectengine** [comment]
https://youtube.com/live/f3dbxzgf6i8
