### ISSUE TITLE
Lies, Damn Lies...and Techempower

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#218]
Proposed Title: Lies, Damn Lies...and Techempower
Proposed Description: Francesco Nigro joins us to discuss the Techempower benchmarks and Quarkus performance.

Guests: Francesco Nigro
Twitter:  @forked_franz

**Comment by franz1981** [comment]
Great , we just need the legals to review the content in case, just in case :) wdyt?

**Comment by insectengine** [comment]
https://youtube.com/live/m48IDNTxJcM
