### ISSUE TITLE
Quarkus Web-Lab Part 2 - Blog and Comments

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#222]
Title: Quarkus Web-Lab Part 2 - Blog and Comments
Long description: Don’t miss the final episode of this live-coding series with Matheus Cruz and Andy Damevin! Discover how to generate a static website and enhance it with a full-stack microservice for blog comment functionality. Along the way, explore the versatility of Quarkus and see why it’s quickly becoming one of the top stacks for building modern web applications.

Twitter (short) description: Don’t miss the final episode of this live-coding series with Matheus Cruz @mcruzdev1 & Andy Damevin @ia3andy! Discover how to generate a static website with a full-stack microservice for blog comment functionality. See why Quarkus is a top stack for building modern web apps.

Guests: Matheus Cruz & Andy Damevin
Twitter: @mcruzdev1 @ia3andy

**Comment by ia3andy** [comment]
Hey @insectengine, could we re-schedule the part 2, @mcruzdev had something unforeseen that came up. Unless @melloware is available as a backup maybe?

**Comment by melloware** [comment]
I wouldn't want to steal @mcruzdev 's thunder as he has done a lion's share of the work. I think its better to postpone until he is available!

**Comment by insectengine** [comment]
oh no! I hope everything is ok @mcruzdev! 

Is there a date we should move it to?

**Comment by insectengine** [comment]
https://youtube.com/live/qsQo8eaJuTk
