### ISSUE TITLE
DevUI Improvements: Chappie

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#228]
Title: DevUI Improvements with Chappie
Proposed title: Phillip Krüger joins us to discuss Quarkus Chappie, an AI assistant extension for Quarkus Dev Mode that assists developers.

Guest: Phillip Krüger
Twitter: @phillipkruger

**Comment by phillip-kruger** [comment]
Looks good to me.

**Comment by insectengine** [comment]
Excellent! We have a couple open dates. Are you available either September 16th or October 14th?

**Comment by phillip-kruger** [comment]
Both of those should be fine. Let me know

**Comment by insectengine** [comment]
I've sent you an invite for the September 16th session.

How does this sound for a description? 

"Phillip Krüger joins us to discuss Quarkus Chappie, an AI assistant extension for Quarkus Dev Mode that assists developers."

**Comment by phillip-kruger** [comment]
@insectengine I think this will be QI#180 ? (179 is web lab part 2)

**Comment by insectengine** [comment]
This session is being inserted in as QI#179 since one of the guests of  web lab part 2 had to push back a week (and is now QI#180).

**Comment by phillip-kruger** [comment]
Can we name this "Developer Experience Improvements" ?

Chappie will be part of this, but is not enough to fill an hour, so I'll show some other improvements too

**Comment by insectengine** [comment]
Since the systems have been updated, I'll update what I can.

**Comment by insectengine** [comment]
Some socials already went out with the old name. I edited what I can and updated the rest for the next set.

**Comment by insectengine** [comment]
https://youtube.com/live/1PJNbX8eWG0
