### ISSUE TITLE
Quarkus Roq

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#231]
Title: What is Quarkus Roq?
Description: Andy Damevin joins us to discuss Quarkus Roq, which includes tooling for generating a static website from your Quarkus application.

Guest: Andy Damevin
Twitter: @ia3andy

**Comment by insectengine** [comment]
@ia3andy  - Holly, Max and I were discussing potential Quarkus Insights ideas and thought a session on Quarkus Roq would be interesting. I know you're doing the two part session with Matheus this month but perhaps we can do a Roq focusses session later in the year?

**Comment by ia3andy** [comment]
Yes that's a very good idea..

**Comment by insectengine** [comment]
Awesome... How does your November look? We have openings the 4th, 11th and 12th

**Comment by insectengine** [comment]
@ia3andy - Hey, are you available to do the ROQ session on either November 4th, 11th or 18th?

**Comment by ia3andy** [comment]
Hey @insectengine thanks for pinging me, November 11th seems good! Thanks

**Comment by insectengine** [comment]
@ia3andy - Excellent... invite sent!

**Comment by mcruzdev** [comment]
Hi @insectengine, how are you?

I talked to @ia3andy  and it would be very interesting for me to participate too :)

**Comment by ia3andy** [comment]
Thanks @mcruzdev will cover the Roq Data part

**Comment by ia3andy** [comment]
@melloware you are welcome to the party to discuss your contributions (seo, rss) and general feeling about Roq

**Comment by melloware** [comment]
Sure if James invites me I will definitely attend!

**Comment by mcruzdev** [comment]
The Roq trio!

**Comment by insectengine** [comment]
Added!

**Comment by insectengine** [comment]
https://www.youtube.com/live/hrF1a5sKqBI
