### ISSUE TITLE
What’s new with JHipster?

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#232]
Proposed Title: What’s new with JHipster?
Proposed Description: Matt Raible joins us to discuss the latest improvements and features of JHipster.

Guest: Matt Raible
Twitter: @mraible

**Comment by insectengine** [comment]
~Matt Raible no longer active with JHipster.~

**Comment by mraible** [comment]
I'm still active with JHipster! I just haven't contributed much lately to the Quarkus blueprint. 🙂

**Comment by insectengine** [comment]
I stand corrected. ;)
