### ISSUE TITLE
Developer improvements with LangChain4j

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#233]
Proposed Title: Developer improvements with LangChain4j
Proposed Description: Georgios Andrianakis & Dimitris Andreadis join us to discuss how the team is leveraging LangChain4j to improve the developer experience.

Guest: Georgios Andrianakis & Dimitris Andreadis
twitter: @geoand86, @dandreadis

**Comment by insectengine** [comment]
@geoand  @dandreadis  - Are y'all open on any of these dates? November 4th, 11th or 18th (or all of December)

**Comment by geoand** [comment]
Things will likely be pretty crazy for me in November, but I assume the 18th will work

**Comment by insectengine** [comment]
@geoand  @dandreadis  - I put this on the calendar for November 18th. I've updated the calendar invite with the info...but you two are already on the invite.

**Comment by insectengine** [comment]
https://www.youtube.com/live/4GpTLqSQa4Q
