### ISSUE TITLE
JDiameter on Quarkus

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#235]
Proposed Title: JDiameter on Quarkus
Proposed Description: Eddie Carpenter joins us to discuss how the Quarkus JDiameter extension modernizes a older telecom protocol with Microservices.

Guest: Eddie Carpenter
Twitter: @CarpenterE37944

**Comment by eddiecarpenter** [comment]
Hi James,

Thanks for the invite. Yes, I would love to be part of the podcast. 

Can you give me some pointers as to what to expect?

Eddie

**Comment by insectengine** [comment]
Excellent! The podcasts are really casual conversations about the topics. If you have code to show or walk through, that's even better as we want to avoid just clicking through slides. This podcast is for a technical audience so feel free to dive into the details!

We use restream as our broadcast app. We can also arrange a quick session before hand to test out the setup.

We have the weekly guest(s) login into the streaming app about 15 minutes prior to make sure all is working and good to go. 

Can you email me at jcobb(at) redhat.com?

**Comment by insectengine** [comment]
Hello @eddiecarpenter,

Are you available to do the session on September 30th?

**Comment by insectengine** [comment]
https://youtube.com/live/eOd5RyQljqI
