### ISSUE TITLE
Writing Quarkus Extensions

### ISSUE THREAD

**Issue by dandreadis** [quarkusio/quarkus-insights#32]
I think Peter Palaga could be a good presenter on that, he's written many extensions and AFAIK he had a related talk on the topic.

**Comment by ppalaga** [comment]
👍

**Comment by insectengine** [comment]
Hello @ppalaga,

Glad to hear you're interested in joining Max and hosts on the Quarkus Insights Podcast!

I'm working with Max to help confirm the schedule of guests so I wanted to reach out to you and get you on the calendar. The podcast is streamed live on Mondays at 14:00 CET (9am EST - in the US). Of the following dates, which would best fit your schedule?

Available dates:
March 29th
April 5th
April 12th
April 19th
April 26th
 
Thanks,
James

**Comment by ppalaga** [comment]
Let's say March 29th

**Comment by insectengine** [comment]
Excellent! I'll put you on the calendar. We'll get back to you with more instructions and next steps to get you set up.

Thanks!

**Comment by insectengine** [comment]
Scheduled for March 29th, Episode 42.

**Comment by insectengine** [comment]
@ppalaga  - hey Peter, I'm very sorry but I misunderstood Max and now we have a conflict. Is it possible for us to push you a week in April. So the week of April 5th. I spoke with Max and that Monday is Easter and Europe will be basically shut down. Would you be able to do the session on Wednesday April 7th?

I'm so very sorry to keep jerking you around.

**Comment by insectengine** [comment]
Confirmed with Peter to move it to April 7th

**Comment by insectengine** [comment]
https://youtu.be/RZbLwBuKxuw
