### ISSUE TITLE
jhipster

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus-insights#38]
follow up on episode 4 what changed/moved in jhipster

**Comment by maxandersen** [comment]
@spoole167 planning for it

**Comment by spoole167** [comment]
Prefered dates are I suggest the 12th or the 19th of April

**Comment by insectengine** [comment]
@spoole167  - We're booked through April with this on the 12th. Awaiting your confirmation for that date.

**Comment by insectengine** [comment]
https://youtu.be/d4q7j9qjuKM
