### ISSUE TITLE
github bot in quarkus

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus-insights#39]
talk about probot in java/quarkus that provides probot like features but instead of javascript full powered java

**Comment by maxandersen** [comment]
@gsmet just assigning to see who will be the guest :)

**Comment by insectengine** [comment]
@gsmet  - Any suggestions on guest/contact info so we can reach out and get them scheduled?

**Comment by gsmet** [comment]
Well, the guest would be me. I think that's what Max wanted to say :).

**Comment by insectengine** [comment]
@gsmet -  LOL... that makes it easier.

Are you available to do the march 29th episode?

**Comment by insectengine** [comment]
Scheduled for Episode #43 -  April 5th
