### ISSUE TITLE
Quarkus and AWS Lambda Containers

### ISSUE THREAD

**Issue by aaronwalker** [quarkusio/quarkus-insights#45]
I wrote a blog post to try out the recently launched container image support for AWS Lambda

https://www.base2services.com/community/techie/2020/12/04/2020-12-04-quarkus-lambda-containers.html

Which I'd me happy to talk about on a insights episode

**Comment by insectengine** [comment]
@aaronwalker - Can you email me at jcobb@redhat.com so I can add you to the calendar invite?
