### ISSUE TITLE
Continuous Testing in Quarkus 2 Alpha

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus-insights#50]
assuming continous testing gets available in alpha/beta of 2.0 get @stuartwdouglas  on with one of the community members suggestion the feature.

**Comment by insectengine** [comment]
@stuartwdouglas  - Would you feel comfortable doing this in the late may/early june timeframe?

**Comment by stuartwdouglas** [comment]
That should be ok

**Comment by insectengine** [comment]
@stuartwdouglas - Actually, because of the importance of Continous Testing, the team is wanting to move this forward to May 10th... Can you  do that date?

**Comment by stuartwdouglas** [comment]
I can

**Comment by insectengine** [comment]
Awesome... consider yourself booked!

**Comment by insectengine** [comment]
Community member Benjamin Thomas to join the Episode.
