### ISSUE TITLE
Quarkus + GRPC

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus-insights#6]

**Comment by maxandersen** [comment]
pinged @michalszynkiewicz to see if/when feasible.

**Comment by maxandersen** [comment]
@michalszynkiewicz confirmed he is up for it.

**Comment by insectengine** [comment]
@michalszynkiewicz  - Awesome! Can we slot you in for May 17th or 24th?

**Comment by michalszynkiewicz** [comment]
@insectengine yes

**Comment by insectengine** [comment]
@michalszynkiewicz  - Great... Let's book you for May 24th then. I'll send you an invite for your calendar. It will be updated with a week of the event with a login link. 

Thanks!

**Comment by insectengine** [comment]
@michalszynkiewicz  - Can I get you to confirm the 24th so I can finalize the scheduling?

**Comment by michalszynkiewicz** [comment]
@insectengine I confirm the 24th of May

**Comment by insectengine** [comment]
Moved to Wednesday the 26th to avoid a Holiday.
