### ISSUE TITLE
Kotlin on Quarkus 

### ISSUE THREAD

**Issue by n1hility** [quarkusio/quarkus-insights#7]
Insights episode showing how you can develop Kotlin apps with Quarkus

**Comment by maxandersen** [comment]
@evanchooly just assigning you so I can see who we got as potential guest :)

**Comment by maxandersen** [comment]
https://github.com/quarkusio/quarkus/issues/10162 co-routine support being the feature we want in first :)

**Comment by insectengine** [comment]
Justin Lee to present
