### ISSUE TITLE
Performance and costs of reactive libraries in Java

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#90]
Julien Ponge @jponge joins us to discuss the performance of the three major reactive streams compliant libraries used in Java applications: RxJava, Project Reactor, and SmallRye Mutiny.

**Comment by jponge** [comment]
See https://dl.acm.org/doi/10.1145/3486605.3486788 ([PDF](https://dl.acm.org/doi/pdf/10.1145/3486605.3486788))
