### ISSUE TITLE
Quarkus and Java 17

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkus-insights#91]
Guests: Georgios/Clement

**Comment by insectengine** [comment]
@cescoffier @geoand  - Hey guys, I'm working with Max to schedule future episodes for Quarkus Insights. We're looking to schedule a session focused on Quarkus and Java 17 for December 6th. Are either/both of you available and willing to be guests for this?

**Comment by geoand** [comment]
I will almost certainly be available for this.

**Comment by cescoffier** [comment]
It should be ok for me too.

**Comment by insectengine** [comment]
LOL... that's the most emphatic almost committal I've gotten!

Shall I book Clement then and Georgios will be a surprise guest? Or shall we promote both of y'all and Georgios, if you have to bail, we'll have Max make a lame joke about your absence?

**Comment by geoand** [comment]
You can include me, there is a very small chance I won't make it 😎

**Comment by insectengine** [comment]
Ok... I'll book it.

**Comment by insectengine** [comment]
I take it the conversation will be around what's new with Java 17 and how it impacts Quarkus?

How about this...
Title: "What's new with Java 17"
Description: "Georgios Andrianakis and Clement Escouffier discuss the latest updates in Java 17 and how to maximize them in Quarkus."

Does that work or do y'all have a different idea?

**Comment by insectengine** [comment]
Completed: https://youtu.be/j5gyD92lPnQ
