### ISSUE TITLE
First application using code.quarkus

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus-insights#98]
QTip showing how to get the first application running via code.quarkus.io

1. Visit code.quarkus.io
2. Set some of the options, but only include the RestEasy extension
3. Download the zip
4. Extract the zip
5. Run Quarkus (speed up the maven bit, but explain that this is only for first run)
6. Observe the fast Quarkus boot time
7. Visit the Endpoint

**Comment by saumya1singh** [comment]
Let's do it 🚀

**Comment by paulrobinson** [comment]
Thanks @SaumyaSingh1!

**Comment by insectengine** [comment]
It's marked private until Max can review:
https://www.youtube.com/watch?v=WXzvg94Jy0s

**Comment by maxandersen** [comment]
This is great @saumya1singh - love your excitement and clear walk through. You touched on all the key points and even pointed out you don't need to use intellj but can use any other editor/IDE too...and extra points for using Windows too - something we haven't seen much.

@insectengine feel free to make it public!

**Comment by insectengine** [comment]
Will do!

**Comment by insectengine** [comment]
It's live... I've scheduled some social posts on the Quarkus Twitter, Facebook and Linkedin accounts to promote at 9am on Tuesday (to keep it away from other social posts).

**Comment by saumya1singh** [comment]
Thanks @maxandersen and @insectengine :)

**Comment by saumya1singh** [comment]
@insectengine @maxandersen Can I share on my social media handles before Tuesday?

**Comment by insectengine** [comment]
Sure!

**Comment by maxandersen** [comment]
Just realized it's on Ubuntu not windows. The world is broken :) but still good!

**Comment by saumya1singh** [comment]
aah Max, the world is beautiful ;)
The entire process on windows is 98% similar except for the unzipping/extracting thing.  
One of my machines has windows OS and the recording from that PC will look very much similar.
