### ISSUE TITLE
First application using the Quarkus CLI

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus-insights#99]
QTip equivalent to #98, but using the Quarkus CLI instead of code.quarkus

**Comment by saumya1singh** [comment]
I would love to try this too since it's so similar to #98  :)

**Comment by paulrobinson** [comment]
Great, thanks @SaumyaSingh1.

I think it would be worth getting #98 completed first, so that we can try out this format. I think the short introductory QTips are a new format for us.

**Comment by insectengine** [comment]
Currently listed as Private: 
https://www.youtube.com/watch?v=dsIZzXretDg

**Comment by maxandersen** [comment]
Looks great. Good job @saumya1singh. Let's make it public.

**Comment by insectengine** [comment]
Pushed live: 
https://youtu.be/dsIZzXretDg

Scheduled on the Quarkus social channels for Thursday the 13th.
